name: Run Tests on Filling Forms

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default: test_forms
        type: choice
        options:
          - test_forms
          - test_pardot
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: test_forms
        if: "github.event.inputs.deployment_target == 'test_forms'"
        run: |
          cd Tests/test_forms
          pytest -s -v
      - name: test_pardot
        if: "github.event.inputs.deployment_target == 'test_pardot'"
        run: |
          cd Tests/test_pardot
          pytest -s -v
        
          
