name: Run Tests on Filling Forms

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default: Fill_forms
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Fill_forms
        run: pytest -s -v Tests/test_forms

      - name: Commit JSON data changes
        run: |
          git config --local user.email "githubactions@gmail.com"
          git config --local user.name "GitHub"

          git add .
          git commit -m "Update JSON data from tests"
          git push origin master
