name: Run Tests on Filling Forms

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default: Fill_forms
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Fill_forms
        run: pytest -s -v Tests/test_forms || true
             allure generate allure-results -o allure-report
             mv allure-report $GITHUB_WORKSPACE/allure-report
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}


      - name: Commit JSON data changes
        run: |
          git config --local user.email "githubactions@gmail.com"
          git config --local user.name "GitHub"

          git add .
          git commit -m "Update JSON data from tests"
          git push origin master


      - name: Set up Git for GitHub Pages
        run: |
          git config --local user.email "githubactions@gmail.com"
          git config --local user.name "GitHub"
          git checkout -B gh-pages

      - name: Copy Allure Report to gh-pages branch
        run: |
           mkdir allure-report
           cp -r $GITHUB_WORKSPACE/allure-report/* .
           git add .
           git commit -m "Deploy Allure Report"
           git push -f origin gh-pages
        if: always()