#name: Run Tests on Pardot
#
#on:
#  push:
#    paths:
#      - 'Tests/data/pardot_data.py'
#
#jobs:
#
#  test_contact_pardot:
#    runs-on: ubuntu-latest
#    timeout-minutes: 20
#
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v3
#      - name: setup Python
#        uses: actions/setup-python@v4
#        with:
#          python-version: '3.11'
#      - name: Install Chrome
#        run: sudo apt-get install google-chrome-stable
#      - name: Install requirements
#        run: pip install -r requirements.txt
#
#      - name: Run tests Contact Page
#        run: pytest -s -v Tests/test_pardot/test_contact_pardot.py
#        continue-on-error: true
#
#
#  test_report_pardot:
#    runs-on: ubuntu-latest
#    timeout-minutes: 30
#
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v3
#      - name: setup Python
#        uses: actions/setup-python@v4
#        with:
#          python-version: '3.11'
#      - name: Install Chrome
#        run: sudo apt-get install google-chrome-stable
#      - name: Install requirements
#        run: pip install -r requirements.txt
#
#      - name: Run tests Report Pages
#        run: pytest -s -v Tests/test_pardot/test_reports_pardot.py
#        continue-on-error: true
#
#  test_sem_pardot:
#    runs-on: ubuntu-latest
#    timeout-minutes: 30
#
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v3
#      - name: setup Python
#        uses: actions/setup-python@v4
#        with:
#          python-version: '3.11'
#      - name: Install Chrome
#        run: sudo apt-get install google-chrome-stable
#      - name: Install requirements
#        run: pip install -r requirements.txt
#
#      - name: Run tests SEM Pages
#        run: pytest -s -v Tests/test_pardot/test_sem_pardot.py
#        continue-on-error: true


name: Run Tests on Pardot

on:
  push:
    paths:
      - 'Tests/data/pardot_data.py'

permissions:
  contents: write
  pages: write
  id-token: write


jobs:
  download-history:
    runs-on: ubuntu-latest
    name: Download history
    steps:
      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - run: >
          ARTIFACT_ID=$(curl -L
          -H "Accept: application/vnd.github+json"
          -H "X-GitHub-Api-Version: 2022-11-28"
          "https://api.github.com/repos/EvgeniaMakarevich/Skai_testing/actions/artifacts?name=allure-results"
          | python3 -c "import sys, json; print(json.load(sys.stdin)['artifacts'][0]['id']);")
          &&
          curl -L
          -H "Accept: application/vnd.github+json"
          -H "Authorization: Bearer ${{ secrets.TOKEN }}"
          -H "X-GitHub-Api-Version: 2022-11-28"
          https://api.github.com/repos/EvgeniaMakarevich/Skai_testing/actions/artifacts/$ARTIFACT_ID/zip -o artifacts.zip
          &&
          REPORT_ID=$(curl -L
          -H "Accept: application/vnd.github+json"
          -H "X-GitHub-Api-Version: 2022-11-28"
          "https://api.github.com/repos/EvgeniaMakarevich/Skai_testing/actions/artifacts?name=github-pages"
          | python -c "import sys, json; print(json.load(sys.stdin)['artifacts'][0]['id']);")
          &&
          curl -L
          -H "Accept: application/vnd.github+json"
          -H "Authorization: Bearer ${{ secrets.TOKEN }}"
          -H "X-GitHub-Api-Version: 2022-11-28"
          https://api.github.com/repos/EvgeniaMakarevich/Skai_testing/actions/artifacts/$REPORT_ID/zip -o pages.zip


      - run: mkdir allure-results && unzip artifacts.zip -d allure-results
      - run: mkdir old_pages pages_history && unzip pages.zip -d old_pages && tar -xvf old_pages/artifact.tar -C pages_history
      - run: cp pages_history/history/* allure-results && cp -r pages_history/history allure-results

      - name: Store allure history
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path:
            allure-results
          retention-days: 1

  test_contact_pardot:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs: download-history

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable
      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3

      - name: Run tests Contact Page
        run: pytest -s -v Tests/test_pardot/test_contact_pardot.py --alluredir=allure-results
        continue-on-error: true

      - name: Store allure results
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path:
            allure-results
          retention-days: 1


  test_report_pardot:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: download-history

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable
      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3

      - name: Run tests Report Pages
        run: pytest -s -v Tests/test_pardot/test_reports_pardot.py --alluredir=allure-results
        continue-on-error: true

      - name: Store allure results
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path:
            allure-results
          retention-days: 1

  test_sem_pardot:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: download-history

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable
      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3

      - name: Run tests SEM Pages
        run: pytest -s -v Tests/test_pardot/test_sem_pardot.py --alluredir=allure-results
        continue-on-error: true


      - name: Store allure results
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path:
            allure-results
          retention-days: 1



