#name: Run Tests on Pardot
#
#on:
#  push:
#    paths:
#      - 'Tests/data/pardot_data.py'
#
#jobs:
#
#  test_contact_pardot:
#    runs-on: ubuntu-latest
#    timeout-minutes: 20
#
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v3
#      - name: setup Python
#        uses: actions/setup-python@v4
#        with:
#          python-version: '3.11'
#      - name: Install Chrome
#        run: sudo apt-get install google-chrome-stable
#      - name: Install requirements
#        run: pip install -r requirements.txt
#
#      - name: Run tests Contact Page
#        run: pytest -s -v Tests/test_pardot/test_contact_pardot.py
#        continue-on-error: true
#
#
#  test_report_pardot:
#    runs-on: ubuntu-latest
#    timeout-minutes: 30
#
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v3
#      - name: setup Python
#        uses: actions/setup-python@v4
#        with:
#          python-version: '3.11'
#      - name: Install Chrome
#        run: sudo apt-get install google-chrome-stable
#      - name: Install requirements
#        run: pip install -r requirements.txt
#
#      - name: Run tests Report Pages
#        run: pytest -s -v Tests/test_pardot/test_reports_pardot.py
#        continue-on-error: true
#
#  test_sem_pardot:
#    runs-on: ubuntu-latest
#    timeout-minutes: 30
#
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v3
#      - name: setup Python
#        uses: actions/setup-python@v4
#        with:
#          python-version: '3.11'
#      - name: Install Chrome
#        run: sudo apt-get install google-chrome-stable
#      - name: Install requirements
#        run: pip install -r requirements.txt
#
#      - name: Run tests SEM Pages
#        run: pytest -s -v Tests/test_pardot/test_sem_pardot.py
#        continue-on-error: true


name: Run Tests on Pardot

on:
  push:
    paths:
      - 'Tests/data/pardot_data.py'

permissions:
  contents: write
  pages: write
  id-token: write


jobs:
  test_contact_pardot:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable
      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run tests Contact Page
        run: pytest -s -v Tests/test_pardot/test_contact_pardot.py --alluredir=allure-results-pardot
        continue-on-error: true

      - name: Store allure results
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path:
            allure-results-pardot
          retention-days: 1


  test_report_pardot:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable
      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3

      - name: Run tests Report Pages
        run: pytest -s -v Tests/test_pardot/test_reports_pardot.py --alluredir=allure-results-pardot
        continue-on-error: true

      - name: Store allure results
        uses: actions/upload-artifact@v3
        with:
          name: allure-results-pardot
          path:
            allure-results-pardot
          retention-days: 1

  test_sem_pardot:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable
      - name: Install requirements
        run: pip install -r requirements.txt


      - name: Run tests SEM Pages
        run: pytest -s -v Tests/test_pardot/test_sem_pardot.py --alluredir=allure-results-pardot
        continue-on-error: true


      - name: Store allure results-pardot
        uses: actions/upload-artifact@v3
        with:
          name: allure-results-pardot
          path:
            allure-results-pardot
          retention-days: 1



