name: Run Tests on Pardot

on:
  push:
#    branches:
#      - main
    paths:
      - 'Tests/data/pardot_data.py'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable
      - name: Install requirements
        run: pip install -r requirements.txt
#      - name: Install ChromeDriver
#        run: |
#          LATEST_CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE")
#          curl -o /tmp/chromedriver.zip "https://chromedriver.storage.googleapis.com/$LATEST_CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
#          sudo unzip /tmp/chromedriver.zip chromedriver -d /usr/local/bin/
      - name: Run tests if verification_code changed
        run: |
          cd Tests/test_pardot/test_reports_pardot.py
          pytest -s -v
